### ISSUE TITLE
Avoid to show duplicated release notes

### ISSUE THREAD

**Issue by dregatos** [nedap/version-control-ios#14]
**Describe the feature**

<img width="300" alt="image_name" src="https://user-images.githubusercontent.com/4560667/43136695-c95d546c-8f49-11e8-8f20-e08c813da20e.PNG">

As a user of any Nedap Ons apps
I don't want to see duplicated elements on the release note list
So that changes are clear tu me.

**Rules/Acceptance criteria**
* R1: If some of the release notes items of different versions are duplicated (like for instance, "General bug fixing.") don't display that item multiple times.
* R2: Duplicated items should be displayed at the end of the release note list

**Comment by martias** [comment]
Fixed in 65b05688803ce03d5501ba96d6c6728e5a6b4bab
